version: "3.5"
services:
  mysql:
    image: "mysql:8.0"
    restart: "always"
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 1G    
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: "true"
      MYSQL_USER: ${MYSQL_USER}
 #     MYSQL_USER: "aviad"
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
  #    MYSQL_PASSWORD: "password"
      MYSQL_DATABASE: ${MYSQL_DATABASE}
   #   MYSQL_DATABASE: "files"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - application-network

  app:
    build: "."
    restart: always
    deploy:
      # replicas: 1
      replicas: ${APP_REPLICAS}
      resources:
        limits:
          cpus: '0.5'
          memory: 500M
    # Start this container after mysql started 
    depends_on:
      - "mysql"
    environment:
      # We can also create a .env file and put this variables inside it
      MYSQL_HOST: "mysql"
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ${PWD}/:/tmp/
    networks:
      - application-network

  webserver:
    image: "nginx:1.23.4-alpine"
    restart: "always"
    deploy:
      resources:
        limits:
          cpus: '0.3'
          memory: 750M
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    networks:
      - application-network
    ports:
      - '3333:80'
    depends_on:
      - 'app'


networks:
  application-network:
    name: application-network
volumes:
  mysql-data:
    name: mysql-data